# Generated by Django 3.0.5 on 2020-04-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='blog/images/')),
                ('textbox', models.TextField()),
            ],
        ),
    ]
